### ISSUE TITLE
Error: Could not find "stylelint-config-standard"

### ISSUE THREAD

**Issue by AndyOGo** [AndyOGo/stylelint-declaration-strict-value#1]
```sh
Error: Could not find "stylelint-config-standard". Do you need a `configBasedir`?
    at exports.default (/Users/axawinterthur/dev/style-guide/node_modules/stylelint/dist/utils/configurationError.js:8:13)
    at exports.default (/Users/axawinterthur/dev/style-guide/node_modules/stylelint/dist/utils/getModulePath.js:15:36)
    at loadExtendedConfig (/Users/axawinterthur/dev/style-guide/node_modules/stylelint/dist/augmentConfig.js:186:45)
    at /Users/axawinterthur/dev/style-guide/node_modules/stylelint/dist/augmentConfig.js:173:14
```

**Comment by AndyOGo** [comment]
related https://github.com/stylelint/stylelint-config-standard/issues/4
